server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 0638d10a-4d9b-44d5-8d98-21f60c3b7cd6
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 172.16.116.100
    virtual-host: /fengge
    username: fengge
    password: fengge
auth:
  jwt:
    publicKeyPath: D:\\develop\\git_code\\temp\\rsa.pub
    cookieName: GMALL_TOKEN
